/* This file is generated by venus-protocol git-9578cfc5. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_H
#define VCL_PROTOCOL_RENDERER_H

#include "vcl_protocol_renderer_cs.h"
#include "vcl_protocol_renderer_defines.h"
#include "vcl_protocol_renderer_func_ptrs.h"
#include "vcl_protocol_renderer_info.h"
#include "vcl_protocol_renderer_types.h"
#include "vcl_protocol_renderer_handles.h"
#include "vcl_protocol_renderer_dispatches.h"
#include "vcl_protocol_renderer_structs.h"
#include "vcl_protocol_renderer_dummy.h"
#include "vcl_protocol_renderer_transport.h"
#include "vcl_protocol_renderer_platform.h"
#include "vcl_protocol_renderer_device.h"
#include "vcl_protocol_renderer_context.h"
#include "vcl_protocol_renderer_queue.h"
#include "vcl_protocol_renderer_event.h"
#include "vcl_protocol_renderer_memory.h"
#include "vcl_protocol_renderer_kernel.h"
#include "vcl_protocol_renderer_program.h"

#endif /* VCL_PROTOCOL_RENDERER_H */
