/* This file is generated by vcl-protocol.  See vcl_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_HANDLES_H
#define VCL_PROTOCOL_RENDERER_HANDLES_H

#include "vcl_protocol_renderer_types.h"

/* VK_DEFINE_HANDLE(cl_platform_id) */

static inline void
vcl_encode_cl_platform_id(struct vcl_cs_encoder *enc, const cl_platform_id *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_cl_platform_id_temp(struct vcl_cs_decoder *dec, cl_platform_id *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_cl_platform_id_lookup(struct vcl_cs_decoder *dec, cl_platform_id *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (cl_platform_id)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_cl_platform_id_handle(cl_platform_id *val)
{
    *val = (cl_platform_id)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(cl_device_id) */

static inline void
vcl_encode_cl_device_id(struct vcl_cs_encoder *enc, const cl_device_id *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_cl_device_id_temp(struct vcl_cs_decoder *dec, cl_device_id *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_cl_device_id_lookup(struct vcl_cs_decoder *dec, cl_device_id *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (cl_device_id)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_cl_device_id_handle(cl_device_id *val)
{
    *val = (cl_device_id)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(cl_context) */

static inline void
vcl_encode_cl_context(struct vcl_cs_encoder *enc, const cl_context *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_cl_context_temp(struct vcl_cs_decoder *dec, cl_context *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_cl_context_lookup(struct vcl_cs_decoder *dec, cl_context *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (cl_context)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_cl_context_handle(cl_context *val)
{
    *val = (cl_context)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(cl_command_queue) */

static inline void
vcl_encode_cl_command_queue(struct vcl_cs_encoder *enc, const cl_command_queue *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_cl_command_queue_temp(struct vcl_cs_decoder *dec, cl_command_queue *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_cl_command_queue_lookup(struct vcl_cs_decoder *dec, cl_command_queue *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (cl_command_queue)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_cl_command_queue_handle(cl_command_queue *val)
{
    *val = (cl_command_queue)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(cl_mem) */

static inline void
vcl_encode_cl_mem(struct vcl_cs_encoder *enc, const cl_mem *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_cl_mem_temp(struct vcl_cs_decoder *dec, cl_mem *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_cl_mem_lookup(struct vcl_cs_decoder *dec, cl_mem *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (cl_mem)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_cl_mem_handle(cl_mem *val)
{
    *val = (cl_mem)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(cl_program) */

static inline void
vcl_encode_cl_program(struct vcl_cs_encoder *enc, const cl_program *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_cl_program_temp(struct vcl_cs_decoder *dec, cl_program *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_cl_program_lookup(struct vcl_cs_decoder *dec, cl_program *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (cl_program)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_cl_program_handle(cl_program *val)
{
    *val = (cl_program)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(cl_kernel) */

static inline void
vcl_encode_cl_kernel(struct vcl_cs_encoder *enc, const cl_kernel *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_cl_kernel_temp(struct vcl_cs_decoder *dec, cl_kernel *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_cl_kernel_lookup(struct vcl_cs_decoder *dec, cl_kernel *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (cl_kernel)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_cl_kernel_handle(cl_kernel *val)
{
    *val = (cl_kernel)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(cl_event) */

static inline void
vcl_encode_cl_event(struct vcl_cs_encoder *enc, const cl_event *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_cl_event_temp(struct vcl_cs_decoder *dec, cl_event *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_cl_event_lookup(struct vcl_cs_decoder *dec, cl_event *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (cl_event)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_cl_event_handle(cl_event *val)
{
    *val = (cl_event)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

/* VK_DEFINE_HANDLE(cl_sampler) */

static inline void
vcl_encode_cl_sampler(struct vcl_cs_encoder *enc, const cl_sampler *val)
{
    const uint64_t id = vcl_cs_handle_load_id((const void **)val);
    vcl_encode_uint64_t(enc, &id);
}

static inline void
vcl_decode_cl_sampler_temp(struct vcl_cs_decoder *dec, cl_sampler *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    vcl_cs_handle_store_id((void **)val, id);
}

static inline void
vcl_decode_cl_sampler_lookup(struct vcl_cs_decoder *dec, cl_sampler *val)
{
    uint64_t id;
    vcl_decode_uint64_t(dec, &id);
    *val = (cl_sampler)vcl_cs_decoder_lookup_object(dec, id);
}

static inline void
vcl_replace_cl_sampler_handle(cl_sampler *val)
{
    *val = (cl_sampler)(uintptr_t)vcl_cs_get_object_handle((const void **)val);
}

#endif /* VCL_PROTOCOL_RENDERER_HANDLES_H */
