/* This file is generated by vcl-protocol.  See vcl_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_TRANSPORT_H
#define VCL_PROTOCOL_RENDERER_TRANSPORT_H

#include "vcl_protocol_renderer_structs.h"

#pragma GCC diagnostic push
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ >= 12
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

static inline void vcl_decode_clSetReplyBufferMESA_args_temp(struct vcl_cs_decoder *dec, struct vcl_command_clSetReplyBufferMESA *args)
{
    vcl_decode_int32_t(dec, &args->resource_id);
}

static inline void vcl_replace_clSetReplyBufferMESA_args_handle(struct vcl_command_clSetReplyBufferMESA *args)
{
    /* skip args->resource_id */
}

static inline void vcl_encode_clSetReplyBufferMESA_reply(struct vcl_cs_encoder *enc, const struct vcl_command_clSetReplyBufferMESA *args)
{
    vcl_encode_cl_command_type_ext(enc, &(cl_command_type_ext){CL_COMMAND_TYPE_clSetReplyBufferMESA_EXT});

    /* skip args->resource_id */
}


static inline void vcl_dispatch_clSetReplyBufferMESA(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags)
{
    struct vcl_command_clSetReplyBufferMESA args;

    if (!ctx->dispatch_clSetReplyBufferMESA) {
        vcl_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    vcl_decode_clSetReplyBufferMESA_args_temp(ctx->decoder, &args);

    if (!vcl_cs_decoder_get_fatal(ctx->decoder))
        ctx->dispatch_clSetReplyBufferMESA(ctx, &args);

    if ((flags & CL_COMMAND_GENERATE_REPLY_BIT_EXT) && !vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_encode_clSetReplyBufferMESA_reply(ctx->encoder, &args);

    vcl_cs_decoder_reset_temp_pool(ctx->decoder);
}

#pragma GCC diagnostic pop

#endif /* VCL_PROTOCOL_RENDERER_TRANSPORT_H */
