/* This file is generated by vcl-protocol.  See vcl_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_STRUCTS_H
#define VCL_PROTOCOL_RENDERER_STRUCTS_H

#include "vcl_protocol_renderer_handles.h"

#pragma GCC diagnostic push
#if !defined(__clang__) && defined(__GNUC__) && __GNUC__ >= 12
#pragma GCC diagnostic ignored "-Wdangling-pointer"
#endif
#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

/* struct cl_image_format */

static inline void
vcl_encode_cl_image_format(struct vcl_cs_encoder *enc, const cl_image_format *val)
{
    vcl_encode_cl_channel_order(enc, &val->image_channel_order);
    vcl_encode_cl_channel_type(enc, &val->image_channel_data_type);
}

static inline void
vcl_decode_cl_image_format_temp(struct vcl_cs_decoder *dec, cl_image_format *val)
{
    vcl_decode_cl_channel_order(dec, &val->image_channel_order);
    vcl_decode_cl_channel_type(dec, &val->image_channel_data_type);
}

static inline void
vcl_decode_cl_image_format_partial_temp(struct vcl_cs_decoder *dec, cl_image_format *val)
{
    /* skip val->image_channel_order */
    /* skip val->image_channel_data_type */
}

static inline void
vcl_replace_cl_image_format_handle(cl_image_format *val)
{
    /* skip val->image_channel_order */
    /* skip val->image_channel_data_type */
}

#pragma GCC diagnostic pop

#endif /* VCL_PROTOCOL_RENDERER_STRUCTS_H */
