/* This file is generated by vcl-protocol.  See vcl_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_TYPES_H
#define VCL_PROTOCOL_RENDERER_TYPES_H

#include "vcl_protocol_renderer_defines.h"

/* char */

static inline void
vcl_encode_char(struct vcl_cs_encoder *enc, const char *val)
{
    vcl_encode(enc, 4, val, sizeof(*val));
}

static inline void
vcl_decode_char(struct vcl_cs_decoder *dec, char *val)
{
    vcl_decode(dec, 4, val, sizeof(*val));
}

/* uint64_t */

static inline void
vcl_encode_uint64_t(struct vcl_cs_encoder *enc, const uint64_t *val)
{
    vcl_encode(enc, 8, val, sizeof(*val));
}

static inline void
vcl_decode_uint64_t(struct vcl_cs_decoder *dec, uint64_t *val)
{
    vcl_decode(dec, 8, val, sizeof(*val));
}

static inline void
vcl_encode_uint64_t_array(struct vcl_cs_encoder *enc, const uint64_t *val, uint32_t count)
{
    const size_t size = sizeof(*val) * count;
    assert(size >= count);
    vcl_encode(enc, size, val, size);
}

static inline void
vcl_decode_uint64_t_array(struct vcl_cs_decoder *dec, uint64_t *val, uint32_t count)
{
    const size_t size = sizeof(*val) * count;
    assert(size >= count);
    vcl_decode(dec, size, val, size);
}

/* intptr_t */

static inline void
vcl_encode_intptr_t(struct vcl_cs_encoder *enc, const intptr_t *val)
{
    const uint64_t tmp = *val;
    vcl_encode_uint64_t(enc, &tmp);
}

static inline void
vcl_decode_intptr_t(struct vcl_cs_decoder *dec, intptr_t *val)
{
    uint64_t tmp;
    vcl_decode_uint64_t(dec, &tmp);
    *val = tmp;
}

static inline void
vcl_encode_intptr_t_array(struct vcl_cs_encoder *enc, const intptr_t *val, uint32_t count)
{
    if (sizeof(intptr_t) == sizeof(uint64_t)) {
        vcl_encode_uint64_t_array(enc, (const uint64_t *)val, count);
    } else {
        for (uint32_t i = 0; i < count; i++)
            vcl_encode_intptr_t(enc, &val[i]);
    }
}

static inline void
vcl_decode_intptr_t_array(struct vcl_cs_decoder *dec, intptr_t *val, uint32_t count)
{
    if (sizeof(intptr_t) == sizeof(uint64_t)) {
        vcl_decode_uint64_t_array(dec, (uint64_t *)val, count);
    } else {
        for (uint32_t i = 0; i < count; i++)
            vcl_decode_intptr_t(dec, &val[i]);
    }
}

/* size_t */

static inline void
vcl_encode_size_t(struct vcl_cs_encoder *enc, const size_t *val)
{
    const uint64_t tmp = *val;
    vcl_encode_uint64_t(enc, &tmp);
}

static inline void
vcl_decode_size_t(struct vcl_cs_decoder *dec, size_t *val)
{
    uint64_t tmp;
    vcl_decode_uint64_t(dec, &tmp);
    *val = tmp;
}

static inline void
vcl_encode_size_t_array(struct vcl_cs_encoder *enc, const size_t *val, uint32_t count)
{
    if (sizeof(size_t) == sizeof(uint64_t)) {
        vcl_encode_uint64_t_array(enc, (const uint64_t *)val, count);
    } else {
        for (uint32_t i = 0; i < count; i++)
            vcl_encode_size_t(enc, &val[i]);
    }
}

static inline void
vcl_decode_size_t_array(struct vcl_cs_decoder *dec, size_t *val, uint32_t count)
{
    if (sizeof(size_t) == sizeof(uint64_t)) {
        vcl_decode_uint64_t_array(dec, (uint64_t *)val, count);
    } else {
        for (uint32_t i = 0; i < count; i++)
            vcl_decode_size_t(dec, &val[i]);
    }
}

/* opaque blob */

static inline void
vcl_encode_blob_array(struct vcl_cs_encoder *enc, const void *val, size_t size)
{
    vcl_encode(enc, (size + 3) & ~3, val, size);
}

static inline void
vcl_decode_blob_array(struct vcl_cs_decoder *dec, void *val, size_t size)
{
    vcl_decode(dec, (size + 3) & ~3, val, size);
}

/* string */

static inline void
vcl_encode_char_array(struct vcl_cs_encoder *enc, const char *val, size_t size)
{
    assert(size && strlen(val) < size);
    vcl_encode_blob_array(enc, val, size);
}

static inline void
vcl_decode_char_array(struct vcl_cs_decoder *dec, char *val, size_t size)
{
    vcl_decode_blob_array(dec, val, size);
    if (size)
        val[size - 1] = '\0';
    else
        vcl_cs_decoder_set_fatal(dec);
}

/* array size (uint64_t) */

static inline void
vcl_encode_array_size(struct vcl_cs_encoder *enc, uint64_t size)
{
    vcl_encode_uint64_t(enc, &size);
}

static inline uint64_t
vcl_decode_array_size(struct vcl_cs_decoder *dec, uint64_t expected_size)
{
    uint64_t size;
    vcl_decode_uint64_t(dec, &size);
    if (size != expected_size) {
        vcl_cs_decoder_set_fatal(dec);
        size = 0;
    }
    return size;
}

static inline uint64_t
vcl_decode_array_size_unchecked(struct vcl_cs_decoder *dec)
{
    uint64_t size;
    vcl_decode_uint64_t(dec, &size);
    return size;
}

static inline uint64_t
vcl_peek_array_size(struct vcl_cs_decoder *dec)
{
    uint64_t size;
    vcl_cs_decoder_peek(dec, sizeof(size), &size, sizeof(size));
    return size;
}

/* non-array pointer */

static inline bool
vcl_encode_simple_pointer(struct vcl_cs_encoder *enc, const void *val)
{
    vcl_encode_array_size(enc, val ? 1 : 0);
    return val;
}

static inline bool
vcl_decode_simple_pointer(struct vcl_cs_decoder *dec)
{
    return vcl_decode_array_size_unchecked(dec);
}

/* int32_t */

static inline void
vcl_encode_int32_t(struct vcl_cs_encoder *enc, const int32_t *val)
{
    vcl_encode(enc, 4, val, sizeof(*val));
}

static inline void
vcl_decode_int32_t(struct vcl_cs_decoder *dec, int32_t *val)
{
    vcl_decode(dec, 4, val, sizeof(*val));
}

static inline void
vcl_encode_int32_t_array(struct vcl_cs_encoder *enc, const int32_t *val, uint32_t count)
{
    const size_t size = sizeof(*val) * count;
    assert(size >= count);
    vcl_encode(enc, size, val, size);
}

static inline void
vcl_decode_int32_t_array(struct vcl_cs_decoder *dec, int32_t *val, uint32_t count)
{
    const size_t size = sizeof(*val) * count;
    assert(size >= count);
    vcl_decode(dec, size, val, size);
}

/* uint8_t */

static inline void
vcl_encode_uint8_t(struct vcl_cs_encoder *enc, const uint8_t *val)
{
    vcl_encode(enc, 4, val, sizeof(*val));
}

static inline void
vcl_decode_uint8_t(struct vcl_cs_decoder *dec, uint8_t *val)
{
    vcl_decode(dec, 4, val, sizeof(*val));
}

static inline void
vcl_encode_uint8_t_array(struct vcl_cs_encoder *enc, const uint8_t *val, uint32_t count)
{
    const size_t size = sizeof(*val) * count;
    assert(size >= count);
    vcl_encode(enc, (size + 3) & ~3, val, size);
}

static inline void
vcl_decode_uint8_t_array(struct vcl_cs_decoder *dec, uint8_t *val, uint32_t count)
{
    const size_t size = sizeof(*val) * count;
    assert(size >= count);
    vcl_decode(dec, (size + 3) & ~3, val, size);
}

/* uint32_t */

static inline void
vcl_encode_uint32_t(struct vcl_cs_encoder *enc, const uint32_t *val)
{
    vcl_encode(enc, 4, val, sizeof(*val));
}

static inline void
vcl_decode_uint32_t(struct vcl_cs_decoder *dec, uint32_t *val)
{
    vcl_decode(dec, 4, val, sizeof(*val));
}

static inline void
vcl_encode_uint32_t_array(struct vcl_cs_encoder *enc, const uint32_t *val, uint32_t count)
{
    const size_t size = sizeof(*val) * count;
    assert(size >= count);
    vcl_encode(enc, size, val, size);
}

static inline void
vcl_decode_uint32_t_array(struct vcl_cs_decoder *dec, uint32_t *val, uint32_t count)
{
    const size_t size = sizeof(*val) * count;
    assert(size >= count);
    vcl_decode(dec, size, val, size);
}

/* typedef int32_t cl_int */

static inline void
vcl_encode_cl_int(struct vcl_cs_encoder *enc, const cl_int *val)
{
    vcl_encode_int32_t(enc, val);
}

static inline void
vcl_decode_cl_int(struct vcl_cs_decoder *dec, cl_int *val)
{
    vcl_decode_int32_t(dec, val);
}

static inline void
vcl_encode_cl_int_array(struct vcl_cs_encoder *enc, const cl_int *val, uint32_t count)
{
    vcl_encode_int32_t_array(enc, val, count);
}

static inline void
vcl_decode_cl_int_array(struct vcl_cs_decoder *dec, cl_int *val, uint32_t count)
{
    vcl_decode_int32_t_array(dec, val, count);
}

/* typedef uint32_t cl_uint */

static inline void
vcl_encode_cl_uint(struct vcl_cs_encoder *enc, const cl_uint *val)
{
    vcl_encode_uint32_t(enc, val);
}

static inline void
vcl_decode_cl_uint(struct vcl_cs_decoder *dec, cl_uint *val)
{
    vcl_decode_uint32_t(dec, val);
}

static inline void
vcl_encode_cl_uint_array(struct vcl_cs_encoder *enc, const cl_uint *val, uint32_t count)
{
    vcl_encode_uint32_t_array(enc, val, count);
}

static inline void
vcl_decode_cl_uint_array(struct vcl_cs_decoder *dec, cl_uint *val, uint32_t count)
{
    vcl_decode_uint32_t_array(dec, val, count);
}

/* typedef uint64_t cl_ulong */

static inline void
vcl_encode_cl_ulong(struct vcl_cs_encoder *enc, const cl_ulong *val)
{
    vcl_encode_uint64_t(enc, val);
}

static inline void
vcl_decode_cl_ulong(struct vcl_cs_decoder *dec, cl_ulong *val)
{
    vcl_decode_uint64_t(dec, val);
}

static inline void
vcl_encode_cl_ulong_array(struct vcl_cs_encoder *enc, const cl_ulong *val, uint32_t count)
{
    vcl_encode_uint64_t_array(enc, val, count);
}

static inline void
vcl_decode_cl_ulong_array(struct vcl_cs_decoder *dec, cl_ulong *val, uint32_t count)
{
    vcl_decode_uint64_t_array(dec, val, count);
}

/* typedef cl_ulong cl_bitfield */

static inline void
vcl_encode_cl_bitfield(struct vcl_cs_encoder *enc, const cl_bitfield *val)
{
    vcl_encode_cl_ulong(enc, val);
}

static inline void
vcl_decode_cl_bitfield(struct vcl_cs_decoder *dec, cl_bitfield *val)
{
    vcl_decode_cl_ulong(dec, val);
}

/* typedef cl_uint cl_bool */

static inline void
vcl_encode_cl_bool(struct vcl_cs_encoder *enc, const cl_bool *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_bool(struct vcl_cs_decoder *dec, cl_bool *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_ulong cl_properties */

static inline void
vcl_encode_cl_properties(struct vcl_cs_encoder *enc, const cl_properties *val)
{
    vcl_encode_cl_ulong(enc, val);
}

static inline void
vcl_decode_cl_properties(struct vcl_cs_decoder *dec, cl_properties *val)
{
    vcl_decode_cl_ulong(dec, val);
}

static inline void
vcl_encode_cl_properties_array(struct vcl_cs_encoder *enc, const cl_properties *val, uint32_t count)
{
    vcl_encode_cl_ulong_array(enc, val, count);
}

static inline void
vcl_decode_cl_properties_array(struct vcl_cs_decoder *dec, cl_properties *val, uint32_t count)
{
    vcl_decode_cl_ulong_array(dec, val, count);
}

/* typedef cl_uint cl_platform_info */

static inline void
vcl_encode_cl_platform_info(struct vcl_cs_encoder *enc, const cl_platform_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_platform_info(struct vcl_cs_decoder *dec, cl_platform_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_device_info */

static inline void
vcl_encode_cl_device_info(struct vcl_cs_encoder *enc, const cl_device_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_device_info(struct vcl_cs_decoder *dec, cl_device_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_device_mem_cache_type */

static inline void
vcl_encode_cl_device_mem_cache_type(struct vcl_cs_encoder *enc, const cl_device_mem_cache_type *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_device_mem_cache_type(struct vcl_cs_decoder *dec, cl_device_mem_cache_type *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_device_local_mem_type */

static inline void
vcl_encode_cl_device_local_mem_type(struct vcl_cs_encoder *enc, const cl_device_local_mem_type *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_device_local_mem_type(struct vcl_cs_decoder *dec, cl_device_local_mem_type *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef intptr_t cl_device_partition_property */

static inline void
vcl_encode_cl_device_partition_property(struct vcl_cs_encoder *enc, const cl_device_partition_property *val)
{
    vcl_encode_intptr_t(enc, val);
}

static inline void
vcl_decode_cl_device_partition_property(struct vcl_cs_decoder *dec, cl_device_partition_property *val)
{
    vcl_decode_intptr_t(dec, val);
}

static inline void
vcl_encode_cl_device_partition_property_array(struct vcl_cs_encoder *enc, const cl_device_partition_property *val, uint32_t count)
{
    vcl_encode_intptr_t_array(enc, val, count);
}

static inline void
vcl_decode_cl_device_partition_property_array(struct vcl_cs_decoder *dec, cl_device_partition_property *val, uint32_t count)
{
    vcl_decode_intptr_t_array(dec, val, count);
}

/* typedef intptr_t cl_context_properties */

static inline void
vcl_encode_cl_context_properties(struct vcl_cs_encoder *enc, const cl_context_properties *val)
{
    vcl_encode_intptr_t(enc, val);
}

static inline void
vcl_decode_cl_context_properties(struct vcl_cs_decoder *dec, cl_context_properties *val)
{
    vcl_decode_intptr_t(dec, val);
}

static inline void
vcl_encode_cl_context_properties_array(struct vcl_cs_encoder *enc, const cl_context_properties *val, uint32_t count)
{
    vcl_encode_intptr_t_array(enc, val, count);
}

static inline void
vcl_decode_cl_context_properties_array(struct vcl_cs_decoder *dec, cl_context_properties *val, uint32_t count)
{
    vcl_decode_intptr_t_array(dec, val, count);
}

/* typedef cl_uint cl_context_info */

static inline void
vcl_encode_cl_context_info(struct vcl_cs_encoder *enc, const cl_context_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_context_info(struct vcl_cs_decoder *dec, cl_context_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_properties cl_queue_properties */

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_encode_cl_queue_properties(struct vcl_cs_encoder *enc, const cl_queue_properties *val)
{
    vcl_encode_cl_properties(enc, val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_decode_cl_queue_properties(struct vcl_cs_decoder *dec, cl_queue_properties *val)
{
    vcl_decode_cl_properties(dec, val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_encode_cl_queue_properties_array(struct vcl_cs_encoder *enc, const cl_queue_properties *val, uint32_t count)
{
    vcl_encode_cl_properties_array(enc, val, count);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_decode_cl_queue_properties_array(struct vcl_cs_decoder *dec, cl_queue_properties *val, uint32_t count)
{
    vcl_decode_cl_properties_array(dec, val, count);
}
#endif // CL_API_SUFFIX__VERSION_2_0

/* typedef cl_uint cl_command_queue_info */

static inline void
vcl_encode_cl_command_queue_info(struct vcl_cs_encoder *enc, const cl_command_queue_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_command_queue_info(struct vcl_cs_decoder *dec, cl_command_queue_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_channel_order */

static inline void
vcl_encode_cl_channel_order(struct vcl_cs_encoder *enc, const cl_channel_order *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_channel_order(struct vcl_cs_decoder *dec, cl_channel_order *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_channel_type */

static inline void
vcl_encode_cl_channel_type(struct vcl_cs_encoder *enc, const cl_channel_type *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_channel_type(struct vcl_cs_decoder *dec, cl_channel_type *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_mem_object_type */

static inline void
vcl_encode_cl_mem_object_type(struct vcl_cs_encoder *enc, const cl_mem_object_type *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_mem_object_type(struct vcl_cs_decoder *dec, cl_mem_object_type *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_mem_info */

static inline void
vcl_encode_cl_mem_info(struct vcl_cs_encoder *enc, const cl_mem_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_mem_info(struct vcl_cs_decoder *dec, cl_mem_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_properties cl_mem_properties */

static inline void
vcl_encode_cl_mem_properties(struct vcl_cs_encoder *enc, const cl_mem_properties *val)
{
    vcl_encode_cl_properties(enc, val);
}

static inline void
vcl_decode_cl_mem_properties(struct vcl_cs_decoder *dec, cl_mem_properties *val)
{
    vcl_decode_cl_properties(dec, val);
}

static inline void
vcl_encode_cl_mem_properties_array(struct vcl_cs_encoder *enc, const cl_mem_properties *val, uint32_t count)
{
    vcl_encode_cl_properties_array(enc, val, count);
}

static inline void
vcl_decode_cl_mem_properties_array(struct vcl_cs_decoder *dec, cl_mem_properties *val, uint32_t count)
{
    vcl_decode_cl_properties_array(dec, val, count);
}

/* typedef cl_uint cl_image_info */

static inline void
vcl_encode_cl_image_info(struct vcl_cs_encoder *enc, const cl_image_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_image_info(struct vcl_cs_decoder *dec, cl_image_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_buffer_create_type */

static inline void
vcl_encode_cl_buffer_create_type(struct vcl_cs_encoder *enc, const cl_buffer_create_type *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_buffer_create_type(struct vcl_cs_decoder *dec, cl_buffer_create_type *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_addressing_mode */

static inline void
vcl_encode_cl_addressing_mode(struct vcl_cs_encoder *enc, const cl_addressing_mode *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_addressing_mode(struct vcl_cs_decoder *dec, cl_addressing_mode *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_filter_mode */

static inline void
vcl_encode_cl_filter_mode(struct vcl_cs_encoder *enc, const cl_filter_mode *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_filter_mode(struct vcl_cs_decoder *dec, cl_filter_mode *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_sampler_info */

static inline void
vcl_encode_cl_sampler_info(struct vcl_cs_encoder *enc, const cl_sampler_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_sampler_info(struct vcl_cs_decoder *dec, cl_sampler_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef intptr_t cl_pipe_properties */

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_encode_cl_pipe_properties(struct vcl_cs_encoder *enc, const cl_pipe_properties *val)
{
    vcl_encode_intptr_t(enc, val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_decode_cl_pipe_properties(struct vcl_cs_decoder *dec, cl_pipe_properties *val)
{
    vcl_decode_intptr_t(dec, val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_encode_cl_pipe_properties_array(struct vcl_cs_encoder *enc, const cl_pipe_properties *val, uint32_t count)
{
    vcl_encode_intptr_t_array(enc, val, count);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_decode_cl_pipe_properties_array(struct vcl_cs_decoder *dec, cl_pipe_properties *val, uint32_t count)
{
    vcl_decode_intptr_t_array(dec, val, count);
}
#endif // CL_API_SUFFIX__VERSION_2_0

/* typedef cl_uint cl_pipe_info */

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_encode_cl_pipe_info(struct vcl_cs_encoder *enc, const cl_pipe_info *val)
{
    vcl_encode_cl_uint(enc, val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_decode_cl_pipe_info(struct vcl_cs_decoder *dec, cl_pipe_info *val)
{
    vcl_decode_cl_uint(dec, val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

/* typedef cl_uint cl_program_info */

static inline void
vcl_encode_cl_program_info(struct vcl_cs_encoder *enc, const cl_program_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_program_info(struct vcl_cs_decoder *dec, cl_program_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_program_build_info */

static inline void
vcl_encode_cl_program_build_info(struct vcl_cs_encoder *enc, const cl_program_build_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_program_build_info(struct vcl_cs_decoder *dec, cl_program_build_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_program_binary_type */

static inline void
vcl_encode_cl_program_binary_type(struct vcl_cs_encoder *enc, const cl_program_binary_type *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_program_binary_type(struct vcl_cs_decoder *dec, cl_program_binary_type *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_int cl_build_status */

static inline void
vcl_encode_cl_build_status(struct vcl_cs_encoder *enc, const cl_build_status *val)
{
    vcl_encode_cl_int(enc, val);
}

static inline void
vcl_decode_cl_build_status(struct vcl_cs_decoder *dec, cl_build_status *val)
{
    vcl_decode_cl_int(dec, val);
}

/* typedef cl_uint cl_kernel_info */

static inline void
vcl_encode_cl_kernel_info(struct vcl_cs_encoder *enc, const cl_kernel_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_kernel_info(struct vcl_cs_decoder *dec, cl_kernel_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_kernel_arg_info */

static inline void
vcl_encode_cl_kernel_arg_info(struct vcl_cs_encoder *enc, const cl_kernel_arg_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_kernel_arg_info(struct vcl_cs_decoder *dec, cl_kernel_arg_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_kernel_arg_address_qualifier */

static inline void
vcl_encode_cl_kernel_arg_address_qualifier(struct vcl_cs_encoder *enc, const cl_kernel_arg_address_qualifier *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_kernel_arg_address_qualifier(struct vcl_cs_decoder *dec, cl_kernel_arg_address_qualifier *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_kernel_arg_access_qualifier */

static inline void
vcl_encode_cl_kernel_arg_access_qualifier(struct vcl_cs_encoder *enc, const cl_kernel_arg_access_qualifier *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_kernel_arg_access_qualifier(struct vcl_cs_decoder *dec, cl_kernel_arg_access_qualifier *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_kernel_work_group_info */

static inline void
vcl_encode_cl_kernel_work_group_info(struct vcl_cs_encoder *enc, const cl_kernel_work_group_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_kernel_work_group_info(struct vcl_cs_decoder *dec, cl_kernel_work_group_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_kernel_sub_group_info */

#ifdef CL_API_SUFFIX__VERSION_2_1
static inline void
vcl_encode_cl_kernel_sub_group_info(struct vcl_cs_encoder *enc, const cl_kernel_sub_group_info *val)
{
    vcl_encode_cl_uint(enc, val);
}
#endif // CL_API_SUFFIX__VERSION_2_1

#ifdef CL_API_SUFFIX__VERSION_2_1
static inline void
vcl_decode_cl_kernel_sub_group_info(struct vcl_cs_decoder *dec, cl_kernel_sub_group_info *val)
{
    vcl_decode_cl_uint(dec, val);
}
#endif // CL_API_SUFFIX__VERSION_2_1

/* typedef cl_uint cl_event_info */

static inline void
vcl_encode_cl_event_info(struct vcl_cs_encoder *enc, const cl_event_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_event_info(struct vcl_cs_decoder *dec, cl_event_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_command_type */

static inline void
vcl_encode_cl_command_type(struct vcl_cs_encoder *enc, const cl_command_type *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_command_type(struct vcl_cs_decoder *dec, cl_command_type *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_uint cl_profiling_info */

static inline void
vcl_encode_cl_profiling_info(struct vcl_cs_encoder *enc, const cl_profiling_info *val)
{
    vcl_encode_cl_uint(enc, val);
}

static inline void
vcl_decode_cl_profiling_info(struct vcl_cs_decoder *dec, cl_profiling_info *val)
{
    vcl_decode_cl_uint(dec, val);
}

/* typedef cl_properties cl_sampler_properties */

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_encode_cl_sampler_properties(struct vcl_cs_encoder *enc, const cl_sampler_properties *val)
{
    vcl_encode_cl_properties(enc, val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_decode_cl_sampler_properties(struct vcl_cs_decoder *dec, cl_sampler_properties *val)
{
    vcl_decode_cl_properties(dec, val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_encode_cl_sampler_properties_array(struct vcl_cs_encoder *enc, const cl_sampler_properties *val, uint32_t count)
{
    vcl_encode_cl_properties_array(enc, val, count);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_decode_cl_sampler_properties_array(struct vcl_cs_decoder *dec, cl_sampler_properties *val, uint32_t count)
{
    vcl_decode_cl_properties_array(dec, val, count);
}
#endif // CL_API_SUFFIX__VERSION_2_0

/* typedef cl_uint cl_kernel_exec_info */

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_encode_cl_kernel_exec_info(struct vcl_cs_encoder *enc, const cl_kernel_exec_info *val)
{
    vcl_encode_cl_uint(enc, val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_decode_cl_kernel_exec_info(struct vcl_cs_decoder *dec, cl_kernel_exec_info *val)
{
    vcl_decode_cl_uint(dec, val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

/* typedef cl_uint cl_khronos_vendor_id */

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void
vcl_encode_cl_khronos_vendor_id(struct vcl_cs_encoder *enc, const cl_khronos_vendor_id *val)
{
    vcl_encode_cl_uint(enc, val);
}
#endif // CL_API_SUFFIX__VERSION_3_0

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void
vcl_decode_cl_khronos_vendor_id(struct vcl_cs_decoder *dec, cl_khronos_vendor_id *val)
{
    vcl_decode_cl_uint(dec, val);
}
#endif // CL_API_SUFFIX__VERSION_3_0

/* typedef cl_uint cl_version */

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void
vcl_encode_cl_version(struct vcl_cs_encoder *enc, const cl_version *val)
{
    vcl_encode_cl_uint(enc, val);
}
#endif // CL_API_SUFFIX__VERSION_3_0

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void
vcl_decode_cl_version(struct vcl_cs_decoder *dec, cl_version *val)
{
    vcl_decode_cl_uint(dec, val);
}
#endif // CL_API_SUFFIX__VERSION_3_0

/* typedef VkFlags64 cl_device_type */

static inline void
vcl_encode_cl_device_type(struct vcl_cs_encoder *enc, const cl_device_type *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}

static inline void
vcl_decode_cl_device_type(struct vcl_cs_decoder *dec, cl_device_type *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}

/* typedef VkFlags64 cl_device_fp_config */

static inline void
vcl_encode_cl_device_fp_config(struct vcl_cs_encoder *enc, const cl_device_fp_config *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}

static inline void
vcl_decode_cl_device_fp_config(struct vcl_cs_decoder *dec, cl_device_fp_config *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}

/* typedef VkFlags64 cl_device_exec_capabilities */

static inline void
vcl_encode_cl_device_exec_capabilities(struct vcl_cs_encoder *enc, const cl_device_exec_capabilities *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}

static inline void
vcl_decode_cl_device_exec_capabilities(struct vcl_cs_decoder *dec, cl_device_exec_capabilities *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}

/* typedef VkFlags64 cl_device_svm_capabilities */

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_encode_cl_device_svm_capabilities(struct vcl_cs_encoder *enc, const cl_device_svm_capabilities *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

#ifdef CL_API_SUFFIX__VERSION_2_0
static inline void
vcl_decode_cl_device_svm_capabilities(struct vcl_cs_decoder *dec, cl_device_svm_capabilities *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}
#endif // CL_API_SUFFIX__VERSION_2_0

/* typedef VkFlags64 cl_command_queue_properties */

static inline void
vcl_encode_cl_command_queue_properties(struct vcl_cs_encoder *enc, const cl_command_queue_properties *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}

static inline void
vcl_decode_cl_command_queue_properties(struct vcl_cs_decoder *dec, cl_command_queue_properties *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}

static inline void
vcl_encode_cl_command_queue_properties_array(struct vcl_cs_encoder *enc, const cl_command_queue_properties *val, uint32_t count)
{
    vcl_encode_uint64_t_array(enc, (const uint64_t *)val, count);
}

static inline void
vcl_decode_cl_command_queue_properties_array(struct vcl_cs_decoder *dec, cl_command_queue_properties *val, uint32_t count)
{
    vcl_decode_uint64_t_array(dec, (uint64_t *)val, count);
}

/* typedef VkFlags64 cl_device_affinity_domain */

static inline void
vcl_encode_cl_device_affinity_domain(struct vcl_cs_encoder *enc, const cl_device_affinity_domain *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}

static inline void
vcl_decode_cl_device_affinity_domain(struct vcl_cs_decoder *dec, cl_device_affinity_domain *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}

/* typedef VkFlags64 cl_mem_flags */

static inline void
vcl_encode_cl_mem_flags(struct vcl_cs_encoder *enc, const cl_mem_flags *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}

static inline void
vcl_decode_cl_mem_flags(struct vcl_cs_decoder *dec, cl_mem_flags *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}

/* typedef VkFlags64 cl_mem_migration_flags */

static inline void
vcl_encode_cl_mem_migration_flags(struct vcl_cs_encoder *enc, const cl_mem_migration_flags *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}

static inline void
vcl_decode_cl_mem_migration_flags(struct vcl_cs_decoder *dec, cl_mem_migration_flags *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}

/* typedef VkFlags64 cl_map_flags */

static inline void
vcl_encode_cl_map_flags(struct vcl_cs_encoder *enc, const cl_map_flags *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}

static inline void
vcl_decode_cl_map_flags(struct vcl_cs_decoder *dec, cl_map_flags *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}

/* typedef VkFlags64 cl_kernel_arg_type_qualifier */

static inline void
vcl_encode_cl_kernel_arg_type_qualifier(struct vcl_cs_encoder *enc, const cl_kernel_arg_type_qualifier *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}

static inline void
vcl_decode_cl_kernel_arg_type_qualifier(struct vcl_cs_decoder *dec, cl_kernel_arg_type_qualifier *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}

/* typedef VkFlags64 cl_device_atomic_capabilities */

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void
vcl_encode_cl_device_atomic_capabilities(struct vcl_cs_encoder *enc, const cl_device_atomic_capabilities *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}
#endif // CL_API_SUFFIX__VERSION_3_0

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void
vcl_decode_cl_device_atomic_capabilities(struct vcl_cs_decoder *dec, cl_device_atomic_capabilities *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}
#endif // CL_API_SUFFIX__VERSION_3_0

/* typedef VkFlags64 cl_device_device_enqueue_capabilities */

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void
vcl_encode_cl_device_device_enqueue_capabilities(struct vcl_cs_encoder *enc, const cl_device_device_enqueue_capabilities *val)
{
    vcl_encode_uint64_t(enc, (const uint64_t *)val);
}
#endif // CL_API_SUFFIX__VERSION_3_0

#ifdef CL_API_SUFFIX__VERSION_3_0
static inline void
vcl_decode_cl_device_device_enqueue_capabilities(struct vcl_cs_decoder *dec, cl_device_device_enqueue_capabilities *val)
{
    vcl_decode_uint64_t(dec, (uint64_t *)val);
}
#endif // CL_API_SUFFIX__VERSION_3_0

/* enum cl_command_flag_bits_ext */

static inline void
vcl_encode_cl_command_flag_bits_ext(struct vcl_cs_encoder *enc, const cl_command_flag_bits_ext *val)
{
    vcl_encode_int32_t(enc, (const int32_t *)val);
}

static inline void
vcl_decode_cl_command_flag_bits_ext(struct vcl_cs_decoder *dec, cl_command_flag_bits_ext *val)
{
    vcl_decode_int32_t(dec, (int32_t *)val);
}

/* enum cl_command_type_ext */

static inline void
vcl_encode_cl_command_type_ext(struct vcl_cs_encoder *enc, const cl_command_type_ext *val)
{
    vcl_encode_int32_t(enc, (const int32_t *)val);
}

static inline void
vcl_decode_cl_command_type_ext(struct vcl_cs_decoder *dec, cl_command_type_ext *val)
{
    vcl_decode_int32_t(dec, (int32_t *)val);
}

#endif /* VCL_PROTOCOL_RENDERER_TYPES_H */
