/* This file is generated by vcl-protocol.  See vcl_protocol_renderer.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_DISPATCHES_H
#define VCL_PROTOCOL_RENDERER_DISPATCHES_H

#include "virgl_util.h"

#include "vcl_protocol_renderer_structs.h"
#include "vcl_protocol_renderer_dummy.h"
#include "vcl_protocol_renderer_transport.h"
#include "vcl_protocol_renderer_platform.h"
#include "vcl_protocol_renderer_device.h"
#include "vcl_protocol_renderer_context.h"
#include "vcl_protocol_renderer_queue.h"
#include "vcl_protocol_renderer_event.h"
#include "vcl_protocol_renderer_memory.h"
#include "vcl_protocol_renderer_kernel.h"
#include "vcl_protocol_renderer_program.h"

static inline const char *vcl_dispatch_command_name(cl_command_type_ext type)
{
    switch (type) {
    case CL_COMMAND_TYPE_clGetPlatformIDs_EXT: return "clGetPlatformIDs";
    case CL_COMMAND_TYPE_clGetPlatformInfo_EXT: return "clGetPlatformInfo";
    case CL_COMMAND_TYPE_clGetDeviceIDs_EXT: return "clGetDeviceIDs";
    case CL_COMMAND_TYPE_clGetDeviceInfo_EXT: return "clGetDeviceInfo";
    case CL_COMMAND_TYPE_clCreateSubDevices_EXT: return "clCreateSubDevices";
    case CL_COMMAND_TYPE_clRetainDevice_EXT: return "clRetainDevice";
    case CL_COMMAND_TYPE_clReleaseDevice_EXT: return "clReleaseDevice";
    case CL_COMMAND_TYPE_clSetDefaultDeviceCommandQueue_EXT: return "clSetDefaultDeviceCommandQueue";
    case CL_COMMAND_TYPE_clGetDeviceAndHostTimer_EXT: return "clGetDeviceAndHostTimer";
    case CL_COMMAND_TYPE_clGetHostTimer_EXT: return "clGetHostTimer";
    case CL_COMMAND_TYPE_clCreateContext_EXT: return "clCreateContext";
    case CL_COMMAND_TYPE_clCreateContextFromType_EXT: return "clCreateContextFromType";
    case CL_COMMAND_TYPE_clRetainContext_EXT: return "clRetainContext";
    case CL_COMMAND_TYPE_clReleaseContext_EXT: return "clReleaseContext";
    case CL_COMMAND_TYPE_clGetContextInfo_EXT: return "clGetContextInfo";
    case CL_COMMAND_TYPE_clCreateCommandQueueWithProperties_EXT: return "clCreateCommandQueueWithProperties";
    case CL_COMMAND_TYPE_clRetainCommandQueue_EXT: return "clRetainCommandQueue";
    case CL_COMMAND_TYPE_clReleaseCommandQueue_EXT: return "clReleaseCommandQueue";
    case CL_COMMAND_TYPE_clGetCommandQueueInfo_EXT: return "clGetCommandQueueInfo";
    case CL_COMMAND_TYPE_clCreatePipe_EXT: return "clCreatePipe";
    case CL_COMMAND_TYPE_clRetainMemObject_EXT: return "clRetainMemObject";
    case CL_COMMAND_TYPE_clReleaseMemObject_EXT: return "clReleaseMemObject";
    case CL_COMMAND_TYPE_clGetSupportedImageFormats_EXT: return "clGetSupportedImageFormats";
    case CL_COMMAND_TYPE_clGetMemObjectInfo_EXT: return "clGetMemObjectInfo";
    case CL_COMMAND_TYPE_clGetImageInfo_EXT: return "clGetImageInfo";
    case CL_COMMAND_TYPE_clCreateSamplerWithProperties_EXT: return "clCreateSamplerWithProperties";
    case CL_COMMAND_TYPE_clRetainSampler_EXT: return "clRetainSampler";
    case CL_COMMAND_TYPE_clReleaseSampler_EXT: return "clReleaseSampler";
    case CL_COMMAND_TYPE_clGetSamplerInfo_EXT: return "clGetSamplerInfo";
    case CL_COMMAND_TYPE_clCreateProgramWithSource_EXT: return "clCreateProgramWithSource";
    case CL_COMMAND_TYPE_clCreateProgramWithBuiltInKernels_EXT: return "clCreateProgramWithBuiltInKernels";
    case CL_COMMAND_TYPE_clRetainProgram_EXT: return "clRetainProgram";
    case CL_COMMAND_TYPE_clReleaseProgram_EXT: return "clReleaseProgram";
    case CL_COMMAND_TYPE_clBuildProgram_EXT: return "clBuildProgram";
    case CL_COMMAND_TYPE_clCompileProgram_EXT: return "clCompileProgram";
    case CL_COMMAND_TYPE_clUnloadPlatformCompiler_EXT: return "clUnloadPlatformCompiler";
    case CL_COMMAND_TYPE_clGetProgramInfo_EXT: return "clGetProgramInfo";
    case CL_COMMAND_TYPE_clGetProgramBuildInfo_EXT: return "clGetProgramBuildInfo";
    case CL_COMMAND_TYPE_clCreateKernel_EXT: return "clCreateKernel";
    case CL_COMMAND_TYPE_clCreateKernelsInProgram_EXT: return "clCreateKernelsInProgram";
    case CL_COMMAND_TYPE_clCloneKernel_EXT: return "clCloneKernel";
    case CL_COMMAND_TYPE_clRetainKernel_EXT: return "clRetainKernel";
    case CL_COMMAND_TYPE_clReleaseKernel_EXT: return "clReleaseKernel";
    case CL_COMMAND_TYPE_clSetKernelArg_EXT: return "clSetKernelArg";
    case CL_COMMAND_TYPE_clSetKernelArgSVMPointer_EXT: return "clSetKernelArgSVMPointer";
    case CL_COMMAND_TYPE_clSetKernelExecInfo_EXT: return "clSetKernelExecInfo";
    case CL_COMMAND_TYPE_clGetKernelInfo_EXT: return "clGetKernelInfo";
    case CL_COMMAND_TYPE_clGetKernelArgInfo_EXT: return "clGetKernelArgInfo";
    case CL_COMMAND_TYPE_clGetKernelWorkGroupInfo_EXT: return "clGetKernelWorkGroupInfo";
    case CL_COMMAND_TYPE_clGetKernelSubGroupInfo_EXT: return "clGetKernelSubGroupInfo";
    case CL_COMMAND_TYPE_clWaitForEvents_EXT: return "clWaitForEvents";
    case CL_COMMAND_TYPE_clGetEventInfo_EXT: return "clGetEventInfo";
    case CL_COMMAND_TYPE_clCreateUserEvent_EXT: return "clCreateUserEvent";
    case CL_COMMAND_TYPE_clRetainEvent_EXT: return "clRetainEvent";
    case CL_COMMAND_TYPE_clReleaseEvent_EXT: return "clReleaseEvent";
    case CL_COMMAND_TYPE_clSetUserEventStatus_EXT: return "clSetUserEventStatus";
    case CL_COMMAND_TYPE_clSetEventCallback_EXT: return "clSetEventCallback";
    case CL_COMMAND_TYPE_clGetEventProfilingInfo_EXT: return "clGetEventProfilingInfo";
    case CL_COMMAND_TYPE_clFlush_EXT: return "clFlush";
    case CL_COMMAND_TYPE_clFinish_EXT: return "clFinish";
    case CL_COMMAND_TYPE_clEnqueueReadBuffer_EXT: return "clEnqueueReadBuffer";
    case CL_COMMAND_TYPE_clEnqueueWriteBuffer_EXT: return "clEnqueueWriteBuffer";
    case CL_COMMAND_TYPE_clEnqueueFillBuffer_EXT: return "clEnqueueFillBuffer";
    case CL_COMMAND_TYPE_clEnqueueCopyBuffer_EXT: return "clEnqueueCopyBuffer";
    case CL_COMMAND_TYPE_clEnqueueCopyBufferRect_EXT: return "clEnqueueCopyBufferRect";
    case CL_COMMAND_TYPE_clEnqueueCopyImage_EXT: return "clEnqueueCopyImage";
    case CL_COMMAND_TYPE_clEnqueueCopyImageToBuffer_EXT: return "clEnqueueCopyImageToBuffer";
    case CL_COMMAND_TYPE_clEnqueueCopyBufferToImage_EXT: return "clEnqueueCopyBufferToImage";
    case CL_COMMAND_TYPE_clEnqueueMigrateMemObjects_EXT: return "clEnqueueMigrateMemObjects";
    case CL_COMMAND_TYPE_clEnqueueNDRangeKernel_EXT: return "clEnqueueNDRangeKernel";
    case CL_COMMAND_TYPE_clEnqueueNativeKernel_EXT: return "clEnqueueNativeKernel";
    case CL_COMMAND_TYPE_clEnqueueMarkerWithWaitList_EXT: return "clEnqueueMarkerWithWaitList";
    case CL_COMMAND_TYPE_clEnqueueBarrierWithWaitList_EXT: return "clEnqueueBarrierWithWaitList";
    case CL_COMMAND_TYPE_clSetCommandQueueProperty_EXT: return "clSetCommandQueueProperty";
    case CL_COMMAND_TYPE_clEnqueueMarker_EXT: return "clEnqueueMarker";
    case CL_COMMAND_TYPE_clEnqueueWaitForEvents_EXT: return "clEnqueueWaitForEvents";
    case CL_COMMAND_TYPE_clEnqueueBarrier_EXT: return "clEnqueueBarrier";
    case CL_COMMAND_TYPE_clUnloadCompiler_EXT: return "clUnloadCompiler";
    case CL_COMMAND_TYPE_clCreateCommandQueue_EXT: return "clCreateCommandQueue";
    case CL_COMMAND_TYPE_clCreateSampler_EXT: return "clCreateSampler";
    case CL_COMMAND_TYPE_clEnqueueTask_EXT: return "clEnqueueTask";
    case CL_COMMAND_TYPE_clSetReplyBufferMESA_EXT: return "clSetReplyBufferMESA";
    case CL_COMMAND_TYPE_clCreateContextMESA_EXT: return "clCreateContextMESA";
    case CL_COMMAND_TYPE_clCreateCommandQueueMESA_EXT: return "clCreateCommandQueueMESA";
    case CL_COMMAND_TYPE_clCreateCommandQueueWithPropertiesMESA_EXT: return "clCreateCommandQueueWithPropertiesMESA";
    case CL_COMMAND_TYPE_clCreateUserEventMESA_EXT: return "clCreateUserEventMESA";
    case CL_COMMAND_TYPE_clCreateBufferMESA_EXT: return "clCreateBufferMESA";
    case CL_COMMAND_TYPE_clCreateBufferWithPropertiesMESA_EXT: return "clCreateBufferWithPropertiesMESA";
    case CL_COMMAND_TYPE_clCreateImage2DMESA_EXT: return "clCreateImage2DMESA";
    case CL_COMMAND_TYPE_clCreateImage3DMESA_EXT: return "clCreateImage3DMESA";
    case CL_COMMAND_TYPE_clCreateKernelMESA_EXT: return "clCreateKernelMESA";
    case CL_COMMAND_TYPE_clCloneKernelMESA_EXT: return "clCloneKernelMESA";
    case CL_COMMAND_TYPE_clCreateProgramWithSourceMESA_EXT: return "clCreateProgramWithSourceMESA";
    case CL_COMMAND_TYPE_clCreateProgramWithBinaryMESA_EXT: return "clCreateProgramWithBinaryMESA";
    case CL_COMMAND_TYPE_clCreateProgramWithILMESA_EXT: return "clCreateProgramWithILMESA";
    case CL_COMMAND_TYPE_clLinkProgramMESA_EXT: return "clLinkProgramMESA";
    case CL_COMMAND_TYPE_clCreateSamplerMESA_EXT: return "clCreateSamplerMESA";
    case CL_COMMAND_TYPE_clCreateSamplerWithPropertiesMESA_EXT: return "clCreateSamplerWithPropertiesMESA";
    case CL_COMMAND_TYPE_clCreateSubBufferMESA_EXT: return "clCreateSubBufferMESA";
    case CL_COMMAND_TYPE_clCreateImageMESA_EXT: return "clCreateImageMESA";
    case CL_COMMAND_TYPE_clCreateImageWithPropertiesMESA_EXT: return "clCreateImageWithPropertiesMESA";
    case CL_COMMAND_TYPE_clEnqueueReadImageMESA_EXT: return "clEnqueueReadImageMESA";
    case CL_COMMAND_TYPE_clEnqueueWriteImageMESA_EXT: return "clEnqueueWriteImageMESA";
    case CL_COMMAND_TYPE_clEnqueueFillImageMESA_EXT: return "clEnqueueFillImageMESA";
    case CL_COMMAND_TYPE_clEnqueueMapBufferMESA_EXT: return "clEnqueueMapBufferMESA";
    case CL_COMMAND_TYPE_clEnqueueMapImageMESA_EXT: return "clEnqueueMapImageMESA";
    case CL_COMMAND_TYPE_clEnqueueUnmapMemObjectMESA_EXT: return "clEnqueueUnmapMemObjectMESA";
    case CL_COMMAND_TYPE_clEnqueueNDRangeKernelMESA_EXT: return "clEnqueueNDRangeKernelMESA";
    case CL_COMMAND_TYPE_clSetContextDestructorCallback_EXT: return "clSetContextDestructorCallback";
    case CL_COMMAND_TYPE_clCreateBuffer_EXT: return "clCreateBuffer";
    case CL_COMMAND_TYPE_clCreateBufferWithProperties_EXT: return "clCreateBufferWithProperties";
    case CL_COMMAND_TYPE_clCreateSubBuffer_EXT: return "clCreateSubBuffer";
    case CL_COMMAND_TYPE_clCreateImage_EXT: return "clCreateImage";
    case CL_COMMAND_TYPE_clCreateImageWithProperties_EXT: return "clCreateImageWithProperties";
    case CL_COMMAND_TYPE_clGetPipeInfo_EXT: return "clGetPipeInfo";
    case CL_COMMAND_TYPE_clSetMemObjectDestructorCallback_EXT: return "clSetMemObjectDestructorCallback";
    case CL_COMMAND_TYPE_clSVMAlloc_EXT: return "clSVMAlloc";
    case CL_COMMAND_TYPE_clSVMFree_EXT: return "clSVMFree";
    case CL_COMMAND_TYPE_clCreateProgramWithBinary_EXT: return "clCreateProgramWithBinary";
    case CL_COMMAND_TYPE_clCreateProgramWithIL_EXT: return "clCreateProgramWithIL";
    case CL_COMMAND_TYPE_clLinkProgram_EXT: return "clLinkProgram";
    case CL_COMMAND_TYPE_clSetProgramReleaseCallback_EXT: return "clSetProgramReleaseCallback";
    case CL_COMMAND_TYPE_clSetProgramSpecializationConstant_EXT: return "clSetProgramSpecializationConstant";
    case CL_COMMAND_TYPE_clEnqueueReadBufferRect_EXT: return "clEnqueueReadBufferRect";
    case CL_COMMAND_TYPE_clEnqueueWriteBufferRect_EXT: return "clEnqueueWriteBufferRect";
    case CL_COMMAND_TYPE_clEnqueueReadImage_EXT: return "clEnqueueReadImage";
    case CL_COMMAND_TYPE_clEnqueueWriteImage_EXT: return "clEnqueueWriteImage";
    case CL_COMMAND_TYPE_clEnqueueFillImage_EXT: return "clEnqueueFillImage";
    case CL_COMMAND_TYPE_clEnqueueMapBuffer_EXT: return "clEnqueueMapBuffer";
    case CL_COMMAND_TYPE_clEnqueueMapImage_EXT: return "clEnqueueMapImage";
    case CL_COMMAND_TYPE_clEnqueueUnmapMemObject_EXT: return "clEnqueueUnmapMemObject";
    case CL_COMMAND_TYPE_clEnqueueSVMFree_EXT: return "clEnqueueSVMFree";
    case CL_COMMAND_TYPE_clEnqueueSVMMemcpy_EXT: return "clEnqueueSVMMemcpy";
    case CL_COMMAND_TYPE_clEnqueueSVMMemFill_EXT: return "clEnqueueSVMMemFill";
    case CL_COMMAND_TYPE_clEnqueueSVMMap_EXT: return "clEnqueueSVMMap";
    case CL_COMMAND_TYPE_clEnqueueSVMUnmap_EXT: return "clEnqueueSVMUnmap";
    case CL_COMMAND_TYPE_clEnqueueSVMMigrateMem_EXT: return "clEnqueueSVMMigrateMem";
    case CL_COMMAND_TYPE_clGetExtensionFunctionAddressForPlatform_EXT: return "clGetExtensionFunctionAddressForPlatform";
    case CL_COMMAND_TYPE_clCreateImage2D_EXT: return "clCreateImage2D";
    case CL_COMMAND_TYPE_clCreateImage3D_EXT: return "clCreateImage3D";
    case CL_COMMAND_TYPE_clGetExtensionFunctionAddress_EXT: return "clGetExtensionFunctionAddress";
    default: return "unknown";
    }
}

static void (*const vcl_dispatch_table[256])(struct vcl_dispatch_context *ctx, cl_command_flags_ext flags) = {
    [CL_COMMAND_TYPE_clGetPlatformIDs_EXT] = vcl_dispatch_clGetPlatformIDs,
    [CL_COMMAND_TYPE_clGetPlatformInfo_EXT] = vcl_dispatch_clGetPlatformInfo,
    [CL_COMMAND_TYPE_clGetDeviceIDs_EXT] = vcl_dispatch_clGetDeviceIDs,
    [CL_COMMAND_TYPE_clGetDeviceInfo_EXT] = vcl_dispatch_clGetDeviceInfo,
    [CL_COMMAND_TYPE_clCreateSubDevices_EXT] = vcl_dispatch_clCreateSubDevices,
    [CL_COMMAND_TYPE_clRetainDevice_EXT] = vcl_dispatch_clRetainDevice,
    [CL_COMMAND_TYPE_clReleaseDevice_EXT] = vcl_dispatch_clReleaseDevice,
    [CL_COMMAND_TYPE_clSetDefaultDeviceCommandQueue_EXT] = vcl_dispatch_clSetDefaultDeviceCommandQueue,
    [CL_COMMAND_TYPE_clGetDeviceAndHostTimer_EXT] = vcl_dispatch_clGetDeviceAndHostTimer,
    [CL_COMMAND_TYPE_clGetHostTimer_EXT] = vcl_dispatch_clGetHostTimer,
    [CL_COMMAND_TYPE_clCreateContext_EXT] = vcl_dispatch_clCreateContext,
    [CL_COMMAND_TYPE_clCreateContextFromType_EXT] = vcl_dispatch_clCreateContextFromType,
    [CL_COMMAND_TYPE_clRetainContext_EXT] = vcl_dispatch_clRetainContext,
    [CL_COMMAND_TYPE_clReleaseContext_EXT] = vcl_dispatch_clReleaseContext,
    [CL_COMMAND_TYPE_clGetContextInfo_EXT] = vcl_dispatch_clGetContextInfo,
    [CL_COMMAND_TYPE_clCreateCommandQueueWithProperties_EXT] = vcl_dispatch_clCreateCommandQueueWithProperties,
    [CL_COMMAND_TYPE_clRetainCommandQueue_EXT] = vcl_dispatch_clRetainCommandQueue,
    [CL_COMMAND_TYPE_clReleaseCommandQueue_EXT] = vcl_dispatch_clReleaseCommandQueue,
    [CL_COMMAND_TYPE_clGetCommandQueueInfo_EXT] = vcl_dispatch_clGetCommandQueueInfo,
    [CL_COMMAND_TYPE_clCreatePipe_EXT] = vcl_dispatch_clCreatePipe,
    [CL_COMMAND_TYPE_clRetainMemObject_EXT] = vcl_dispatch_clRetainMemObject,
    [CL_COMMAND_TYPE_clReleaseMemObject_EXT] = vcl_dispatch_clReleaseMemObject,
    [CL_COMMAND_TYPE_clGetSupportedImageFormats_EXT] = vcl_dispatch_clGetSupportedImageFormats,
    [CL_COMMAND_TYPE_clGetMemObjectInfo_EXT] = vcl_dispatch_clGetMemObjectInfo,
    [CL_COMMAND_TYPE_clGetImageInfo_EXT] = vcl_dispatch_clGetImageInfo,
    [CL_COMMAND_TYPE_clCreateSamplerWithProperties_EXT] = vcl_dispatch_clCreateSamplerWithProperties,
    [CL_COMMAND_TYPE_clRetainSampler_EXT] = vcl_dispatch_clRetainSampler,
    [CL_COMMAND_TYPE_clReleaseSampler_EXT] = vcl_dispatch_clReleaseSampler,
    [CL_COMMAND_TYPE_clGetSamplerInfo_EXT] = vcl_dispatch_clGetSamplerInfo,
    [CL_COMMAND_TYPE_clCreateProgramWithSource_EXT] = vcl_dispatch_clCreateProgramWithSource,
    [CL_COMMAND_TYPE_clCreateProgramWithBuiltInKernels_EXT] = vcl_dispatch_clCreateProgramWithBuiltInKernels,
    [CL_COMMAND_TYPE_clRetainProgram_EXT] = vcl_dispatch_clRetainProgram,
    [CL_COMMAND_TYPE_clReleaseProgram_EXT] = vcl_dispatch_clReleaseProgram,
    [CL_COMMAND_TYPE_clBuildProgram_EXT] = vcl_dispatch_clBuildProgram,
    [CL_COMMAND_TYPE_clCompileProgram_EXT] = vcl_dispatch_clCompileProgram,
    [CL_COMMAND_TYPE_clUnloadPlatformCompiler_EXT] = vcl_dispatch_clUnloadPlatformCompiler,
    [CL_COMMAND_TYPE_clGetProgramInfo_EXT] = vcl_dispatch_clGetProgramInfo,
    [CL_COMMAND_TYPE_clGetProgramBuildInfo_EXT] = vcl_dispatch_clGetProgramBuildInfo,
    [CL_COMMAND_TYPE_clCreateKernel_EXT] = vcl_dispatch_clCreateKernel,
    [CL_COMMAND_TYPE_clCreateKernelsInProgram_EXT] = vcl_dispatch_clCreateKernelsInProgram,
    [CL_COMMAND_TYPE_clCloneKernel_EXT] = vcl_dispatch_clCloneKernel,
    [CL_COMMAND_TYPE_clRetainKernel_EXT] = vcl_dispatch_clRetainKernel,
    [CL_COMMAND_TYPE_clReleaseKernel_EXT] = vcl_dispatch_clReleaseKernel,
    [CL_COMMAND_TYPE_clSetKernelArg_EXT] = vcl_dispatch_clSetKernelArg,
    [CL_COMMAND_TYPE_clSetKernelArgSVMPointer_EXT] = vcl_dispatch_clSetKernelArgSVMPointer,
    [CL_COMMAND_TYPE_clSetKernelExecInfo_EXT] = vcl_dispatch_clSetKernelExecInfo,
    [CL_COMMAND_TYPE_clGetKernelInfo_EXT] = vcl_dispatch_clGetKernelInfo,
    [CL_COMMAND_TYPE_clGetKernelArgInfo_EXT] = vcl_dispatch_clGetKernelArgInfo,
    [CL_COMMAND_TYPE_clGetKernelWorkGroupInfo_EXT] = vcl_dispatch_clGetKernelWorkGroupInfo,
    [CL_COMMAND_TYPE_clGetKernelSubGroupInfo_EXT] = vcl_dispatch_clGetKernelSubGroupInfo,
    [CL_COMMAND_TYPE_clWaitForEvents_EXT] = vcl_dispatch_clWaitForEvents,
    [CL_COMMAND_TYPE_clGetEventInfo_EXT] = vcl_dispatch_clGetEventInfo,
    [CL_COMMAND_TYPE_clCreateUserEvent_EXT] = vcl_dispatch_clCreateUserEvent,
    [CL_COMMAND_TYPE_clRetainEvent_EXT] = vcl_dispatch_clRetainEvent,
    [CL_COMMAND_TYPE_clReleaseEvent_EXT] = vcl_dispatch_clReleaseEvent,
    [CL_COMMAND_TYPE_clSetUserEventStatus_EXT] = vcl_dispatch_clSetUserEventStatus,
    [CL_COMMAND_TYPE_clSetEventCallback_EXT] = vcl_dispatch_clSetEventCallback,
    [CL_COMMAND_TYPE_clGetEventProfilingInfo_EXT] = vcl_dispatch_clGetEventProfilingInfo,
    [CL_COMMAND_TYPE_clFlush_EXT] = vcl_dispatch_clFlush,
    [CL_COMMAND_TYPE_clFinish_EXT] = vcl_dispatch_clFinish,
    [CL_COMMAND_TYPE_clEnqueueReadBuffer_EXT] = vcl_dispatch_clEnqueueReadBuffer,
    [CL_COMMAND_TYPE_clEnqueueWriteBuffer_EXT] = vcl_dispatch_clEnqueueWriteBuffer,
    [CL_COMMAND_TYPE_clEnqueueFillBuffer_EXT] = vcl_dispatch_clEnqueueFillBuffer,
    [CL_COMMAND_TYPE_clEnqueueCopyBuffer_EXT] = vcl_dispatch_clEnqueueCopyBuffer,
    [CL_COMMAND_TYPE_clEnqueueCopyBufferRect_EXT] = vcl_dispatch_clEnqueueCopyBufferRect,
    [CL_COMMAND_TYPE_clEnqueueCopyImage_EXT] = vcl_dispatch_clEnqueueCopyImage,
    [CL_COMMAND_TYPE_clEnqueueCopyImageToBuffer_EXT] = vcl_dispatch_clEnqueueCopyImageToBuffer,
    [CL_COMMAND_TYPE_clEnqueueCopyBufferToImage_EXT] = vcl_dispatch_clEnqueueCopyBufferToImage,
    [CL_COMMAND_TYPE_clEnqueueMigrateMemObjects_EXT] = vcl_dispatch_clEnqueueMigrateMemObjects,
    [CL_COMMAND_TYPE_clEnqueueNDRangeKernel_EXT] = vcl_dispatch_clEnqueueNDRangeKernel,
    [CL_COMMAND_TYPE_clEnqueueNativeKernel_EXT] = vcl_dispatch_clEnqueueNativeKernel,
    [CL_COMMAND_TYPE_clEnqueueMarkerWithWaitList_EXT] = vcl_dispatch_clEnqueueMarkerWithWaitList,
    [CL_COMMAND_TYPE_clEnqueueBarrierWithWaitList_EXT] = vcl_dispatch_clEnqueueBarrierWithWaitList,
    [CL_COMMAND_TYPE_clSetCommandQueueProperty_EXT] = vcl_dispatch_clSetCommandQueueProperty,
    [CL_COMMAND_TYPE_clEnqueueMarker_EXT] = vcl_dispatch_clEnqueueMarker,
    [CL_COMMAND_TYPE_clEnqueueWaitForEvents_EXT] = vcl_dispatch_clEnqueueWaitForEvents,
    [CL_COMMAND_TYPE_clEnqueueBarrier_EXT] = vcl_dispatch_clEnqueueBarrier,
    [CL_COMMAND_TYPE_clUnloadCompiler_EXT] = vcl_dispatch_clUnloadCompiler,
    [CL_COMMAND_TYPE_clCreateCommandQueue_EXT] = vcl_dispatch_clCreateCommandQueue,
    [CL_COMMAND_TYPE_clCreateSampler_EXT] = vcl_dispatch_clCreateSampler,
    [CL_COMMAND_TYPE_clEnqueueTask_EXT] = vcl_dispatch_clEnqueueTask,
    [CL_COMMAND_TYPE_clSetReplyBufferMESA_EXT] = vcl_dispatch_clSetReplyBufferMESA,
    [CL_COMMAND_TYPE_clCreateContextMESA_EXT] = vcl_dispatch_clCreateContextMESA,
    [CL_COMMAND_TYPE_clCreateCommandQueueMESA_EXT] = vcl_dispatch_clCreateCommandQueueMESA,
    [CL_COMMAND_TYPE_clCreateCommandQueueWithPropertiesMESA_EXT] = vcl_dispatch_clCreateCommandQueueWithPropertiesMESA,
    [CL_COMMAND_TYPE_clCreateUserEventMESA_EXT] = vcl_dispatch_clCreateUserEventMESA,
    [CL_COMMAND_TYPE_clCreateBufferMESA_EXT] = vcl_dispatch_clCreateBufferMESA,
    [CL_COMMAND_TYPE_clCreateBufferWithPropertiesMESA_EXT] = vcl_dispatch_clCreateBufferWithPropertiesMESA,
    [CL_COMMAND_TYPE_clCreateImage2DMESA_EXT] = vcl_dispatch_clCreateImage2DMESA,
    [CL_COMMAND_TYPE_clCreateImage3DMESA_EXT] = vcl_dispatch_clCreateImage3DMESA,
    [CL_COMMAND_TYPE_clCreateKernelMESA_EXT] = vcl_dispatch_clCreateKernelMESA,
    [CL_COMMAND_TYPE_clCloneKernelMESA_EXT] = vcl_dispatch_clCloneKernelMESA,
    [CL_COMMAND_TYPE_clCreateProgramWithSourceMESA_EXT] = vcl_dispatch_clCreateProgramWithSourceMESA,
    [CL_COMMAND_TYPE_clCreateProgramWithBinaryMESA_EXT] = vcl_dispatch_clCreateProgramWithBinaryMESA,
    [CL_COMMAND_TYPE_clCreateProgramWithILMESA_EXT] = vcl_dispatch_clCreateProgramWithILMESA,
    [CL_COMMAND_TYPE_clLinkProgramMESA_EXT] = vcl_dispatch_clLinkProgramMESA,
    [CL_COMMAND_TYPE_clCreateSamplerMESA_EXT] = vcl_dispatch_clCreateSamplerMESA,
    [CL_COMMAND_TYPE_clCreateSamplerWithPropertiesMESA_EXT] = vcl_dispatch_clCreateSamplerWithPropertiesMESA,
    [CL_COMMAND_TYPE_clCreateSubBufferMESA_EXT] = vcl_dispatch_clCreateSubBufferMESA,
    [CL_COMMAND_TYPE_clCreateImageMESA_EXT] = vcl_dispatch_clCreateImageMESA,
    [CL_COMMAND_TYPE_clCreateImageWithPropertiesMESA_EXT] = vcl_dispatch_clCreateImageWithPropertiesMESA,
    [CL_COMMAND_TYPE_clEnqueueReadImageMESA_EXT] = vcl_dispatch_clEnqueueReadImageMESA,
    [CL_COMMAND_TYPE_clEnqueueWriteImageMESA_EXT] = vcl_dispatch_clEnqueueWriteImageMESA,
    [CL_COMMAND_TYPE_clEnqueueFillImageMESA_EXT] = vcl_dispatch_clEnqueueFillImageMESA,
    [CL_COMMAND_TYPE_clEnqueueMapBufferMESA_EXT] = vcl_dispatch_clEnqueueMapBufferMESA,
    [CL_COMMAND_TYPE_clEnqueueMapImageMESA_EXT] = vcl_dispatch_clEnqueueMapImageMESA,
    [CL_COMMAND_TYPE_clEnqueueUnmapMemObjectMESA_EXT] = vcl_dispatch_clEnqueueUnmapMemObjectMESA,
    [CL_COMMAND_TYPE_clEnqueueNDRangeKernelMESA_EXT] = vcl_dispatch_clEnqueueNDRangeKernelMESA,
};

static inline void vcl_dispatch_command(struct vcl_dispatch_context *ctx)
{
    cl_command_type_ext cmd_type;
    cl_command_flags_ext cmd_flags;

    vcl_decode_cl_command_type_ext(ctx->decoder, &cmd_type);
    vcl_decode_cl_command_flag_bits_ext(ctx->decoder, &cmd_flags);

    {
#ifdef DEBUG
        TRACE_SCOPE_SLOW(vcl_dispatch_command_name(cmd_type));
#endif
        if (cmd_type < 256 && vcl_dispatch_table[cmd_type])
            vcl_dispatch_table[cmd_type](ctx, cmd_flags);
        else
            vcl_cs_decoder_set_fatal(ctx->decoder);
    }

    if (vcl_cs_decoder_get_fatal(ctx->decoder))
        vcl_dispatch_debug_log(ctx, "%s resulted in CS error", vcl_dispatch_command_name(cmd_type));
}

#endif /* VCL_PROTOCOL_RENDERER_DISPATCHES_H */
