/* This file is generated by vcl-protocol.  See vcl_protocol_renderer.h. */

/*
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#ifndef VCL_PROTOCOL_RENDERER_FUNC_PTRS_H
#define VCL_PROTOCOL_RENDERER_FUNC_PTRS_H

typedef void (CL_CALLBACK * CB_clEnqueueSVMFreeARM )( cl_command_queue queue, cl_uint num_svm_pointers, void * svm_pointers[], void * user_data);
typedef void (CL_CALLBACK * CB_clCreateContext )( const char * errinfo, const void * private_info, size_t cb, void* user_data);
typedef void (CL_CALLBACK * CB_clCreateContextFromType )( const char * errinfo, const void * private_info, size_t cb, void * user_data);
typedef void (CL_CALLBACK * CB_clSetContextDestructorCallback )( cl_context context, void * user_data);
typedef void (CL_CALLBACK * CB_clSetMemObjectDestructorCallback )( cl_mem memobj, void * user_data);
typedef void (CL_CALLBACK * CB_clSetMemObjectDestructorAPPLE )( cl_mem memobj, void * user_data);
typedef void (CL_CALLBACK * CB_clBuildProgram )( cl_program program, void * user_data);
typedef void (CL_CALLBACK * CB_clCompileProgram )( cl_program program, void * user_data);
typedef void (CL_CALLBACK * CB_clLinkProgram ) ( cl_program program, void * user_data);
typedef void (CL_CALLBACK * CB_clSetProgramReleaseCallback ) ( cl_program program, void * user_data);
typedef void (CL_CALLBACK * CB_clSetEventCallback ) ( cl_event event, cl_int event_command_status, void * user_data);
typedef void (CL_CALLBACK * CB_clEnqueueNativeKernel ) ( void * args);
typedef void (CL_CALLBACK * CB_clEnqueueSVMFree ) ( cl_command_queue queue, cl_uint num_svm_pointers, void * svm_pointers[], void * user_data);

#endif
